version: '3'
services:
  deep_learning_with_pytorch:
    build: .
    working_dir: /workspace
    tty: true
    volumes:
      - ./:/workspace:cached
    ports:
      - 8888:8888
    runtime: nvidia
    shm_size: '2gb'
